kind: Service
apiVersion: v1
metadata:
  name: my-service # Service name
spec:
  type: LoadBalancer
  selector:
    run: my-app # Label selector. The Service targets Pods that use this label
  ports:
  - name: http
    port: 80 # Port used to access the Service from within the cluster.
    targetPort: 8080 # Port opened by targeted Pods